### PR TITLE
ENH: enhance reliability of receiving EDF files at the end of an experiment

### PR DESCRIPTION
**Pull request by mh105**
This PR contains 

- a BF to unregister ioHub keyboard monitor of escape and space releases as discussed [here](https://github.com/psychopy/psychopy/pull/6466).
- ENH commits to make receiving EDF files at the end of an experiment more reliable. Specifically, dependent on the merge of this [PR](https://github.com/psychopy/psychopy/pull/6555) into the main psychopy release, the current PR will use the exposed PsychoPy filename when `dsfile` is `None` to open and download EDF files with the same naming convention as the rest of subject data files. If the saving folder does not exist, we also `mkdir` to make sure we do save the eye tracking data.
- BF around dependency of SR research package `sr-research-pylink` from their own PyPI server.

### CODE REVIEW

**Comment by mh105** [comment]
Apparently the PsychoPy plugin environment manager is quite general as shown [here](https://github.com/psychopy/psychopy/blob/ecc123a768f9ee40340b273c9941092764095d88/psychopy/app/plugin_manager/dialog.py#L81). But that is notably a problem in this situation with a non-PyPI index for installing a dependency. Perhaps you just have to have an if statement to handle this edge case! I'll leave that to the development team to decide how to handle...

**Comment by TEParsons** [comment]
I think the solution is going to be us pestering the eyelink team to put their package on PyPi :P 

I've pulled this in - @mh105 would you mind checking with the latest `psychopy/dev` and `main` branch of this repo installed whether your eyelink is now found and calibrates correctly? If so, I'll queue up a release of this plugin to coincide with the next release of PsychoPy and all these fixes can be live :D

**Comment by mh105** [comment]
In order for some of my commits to work correctly, I need the merge of this PR into the PsychoPy `release` and then into `dev`: https://github.com/psychopy/psychopy/pull/6555

**Comment by mh105** [comment]
@TEParsons Just a gentle reminder to see if you could merge my other PR into PsychoPy `release` and `dev` branches so I can test out whether my EyeLink can be imported correctly using the new `importlib` approach. Thanks!

**Comment by mh105** [comment]
I've tested them - didn't work but after https://github.com/psychopy/psychopy/pull/6610 and https://github.com/psychopy/psychopy-eyetracker-sr-research/pull/10, they work smoothly now 👍

**Pull request merged**
